"""A NAIP source backed by ``naip_<year>.tif`` files in a directory.

Used locally and in tests (``NAIP_SOURCE=fixture``) so discovery, ingest, tiles and runs
all work with no AWS credentials. The committed files are generated by
``tests/fixtures/make_imagery_fixtures.py``.
"""

import re
from pathlib import Path

import rasterio
from rasterio.warp import transform_bounds
from shapely.geometry import box
from shapely.geometry.base import BaseGeometry

from ptax.imagery.sources import NaipItem, NaipYear, group_years

_NAME = re.compile(r"^naip_(\d{4})\.tif$")


class FixtureNaipSource:
    def __init__(self, directory: str | Path) -> None:
        self._dir = Path(directory)

    def list_years(self, footprint: BaseGeometry) -> list[NaipYear]:
        return group_years(self._items(footprint), footprint)

    def items_for(self, year: int, footprint: BaseGeometry) -> list[NaipItem]:
        return [i for i in self._items(footprint) if i.year == year]

    def gdal_env(self) -> dict[str, str]:
        return {}

    def _items(self, footprint: BaseGeometry) -> list[NaipItem]:
        items = []
        for path in sorted(self._dir.glob("naip_*.tif")):
            match = _NAME.match(path.name)
            if not match:
                continue
            with rasterio.open(path) as src:
                bounds = transform_bounds(src.crs, "EPSG:4326", *src.bounds)
                geometry = box(*bounds)
                if not geometry.intersects(footprint):
                    continue
                items.append(
                    NaipItem(
                        id=path.stem,
                        year=int(match.group(1)),
                        href=str(path.resolve()),
                        geometry=geometry,
                        gsd_m=float(src.res[0]),
                        epsg=src.crs.to_epsg() or 0,
                        width=src.width,
                        height=src.height,
                    )
                )
        return items
